### PR TITLE
chore: prework for watching multiple crd

### PR DESCRIPTION
**Pull request by mkramb**
Prework for adding support for ```environments```

* have a common folder for ```kubeclient```
* support watching for multiple ```CRDs```

@jstrachan @rawlingsj

### CODE REVIEW

**Comment by jstrachan** [comment]
then we could have something like...
```typescript
let pipelineWatcher = new KubeWatcher(CRDs.Pipeline);
let envWatcher = new KubeWatcher(CRDs.Environment);
...
pipelineWatcher.addCallback()...
```

**Comment by mkramb** [comment]
@jstrachan i like that approach! will refactor and update PR

**Comment by jstrachan** [comment]
yeah - we may wanna watch other stuff (CRD or k8s resources like Deployment / Service) in other namespaces too so leaving it nice and simple - we pass in a URL or something - should mean we can later on build more complex watchers etc.

e.g. when we're on helm3 we could watch the helm CRDs as releases happen in Staging / Production

**Comment by mkramb** [comment]
@jstrachan updated, so API looks like ```const pipelines = new KubeWatcher(KubeCrd.Pipelines);```

**Pull request merged**
